baseURL: https://ZhongWeichang001.github.io
theme: hugo-theme-LoveIt
languageCode: en
languageName: English
hasCJKLanguage: true
title: ZZC's blog
author:
  name: ZZC
  email: meetzhongwc@gmail.com
menu:
  main:
    - weight: 1
      identifier: posts
      name: Posts
      url: /posts/
    - weight: 2
      identifier: tags
      name: Tags
      url: /tags/
      title:
    - weight: 3
      identifier: categories
      name: Categories
      url: /categories/
      title:
    - weight: 4
      identifier: documentation
      name: Docs
      url: /categories/documentation/
      title:
    - weight: 5
      identifier: about
      name: About
      url: /about/
      title:
    - weight: 6
      identifier: github
      pre: "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
      post: ""
      name: ""
      url: https://github.com/ZhongWeichang001/ZhongWeichang001.github.io
      title: GitHub
params:
  # site default theme ["auto", "light", "dark"]
  defaultTheme: auto
  # public git repo url only then enableGitInfo is true
  gitRepo: https://github.com/ZhongWeichang001/ZhongWeichang001.github.io
  # which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint: sha512
  # date format
  dateFormat: 2006-01-02
  # website title for Open Graph and Twitter Cards
  title: My cool site
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description: This is my cool site
  # website images for Open Graph and Twitter Cards
  images: /images/avatar.jpg
  # Header config
  header:
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode: fixed
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode: auto
    # Header title config
    title:
      # URL of the LOGO
      logo:
      # title name
      name:
      # you can add extra information before the name (HTML format is supported), such as icons
      pre:
      # you can add extra information after the name (HTML format is supported), such as icons
      post:
      # whether to use typeit animation for title name
      typeit: true
  # Footer config
  footer:
    enable: true
    # Custom content (HTML format is supported)
    custom:
    # whether to show Hugo and theme info
    hugo: true
    # whether to show copyright info
    copyright: true
    # whether to show the author
    author: true
    # Site creation time
    since: 2019
    # ICP info only in China (HTML format is supported)
    icp: 
    # license info (HTML format is supported)
    license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # Section (all posts) page config
  section:
    # special amount of posts in each section page
    paginate: 20
    # date format (month and day)
    dateFormat: 01-02
    # amount of RSS pages
    rss: 10
  # List (category or tag) page config
  list:
    # special amount of posts in each section page
    paginate: 20
    # date format (month and day)
    dateFormat: 01-02
    # amount of RSS pages
    rss: 10
  # App icon config
  app:
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title: My cool site
    # whether to omit favicon resource links
    noFavicon: false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon:
    # Android browser theme color
    themeColor: "#ffffff"
    # Safari mask icon color
    iconColor: "#5bbad5"
    # Windows v8-10 tile color
    tileColor: "#da532c"
  # Search config
  search:
    enable: true
    # type of search engine ["lunr", "algolia":
    type: lunr
    # max index length of the chunked content
    contentLength: 4000
    # placeholder of the search bar
    placeholder:
    # max number of results length
    maxResultLength: 10
    # snippet length of the result
    snippetLength: 50
    # HTML tag name of the highlight part in results
    highlightTag: em
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL: false
    algolia:
      index:
      appID:
      searchKey:
  # Home page config
  home:
    # amount of RSS pages
    rss: 10
    # Home page profile
    profile:
      enable: true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail: ""
      # URL of avatar shown in home page
      avatarURL: "/images/avatar.jpg"
      # title shown in home page (HTML format is supported)
      title: ""
      # subtitle shown in home page (HTML format is supported)
      subtitle: This is My New Hugo Site
      # whether to use typeit animation for subtitle
      typeit: true
      # whether to show social links
      social: true
      # disclaimer (HTML format is supported)
      disclaimer: ""
    # Home page posts
    posts:
      enable: true
      # special amount of posts in each home posts page
      paginate: 6
      # replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage: false
  # Social config about the author
  social:
    GitHub: ZhongWeichang001
    Email: meetzhongwc@gmail.com
  # Page global config
  page:
    # whether to hide a page from home page
    hiddenFromHomePage: false
    # whether to hide a page from search results
    hiddenFromSearch: false
    # whether to enable twemoji
    twemoji: false
    # whether to enable lightgallery
    lightgallery: false
    # whether to enable the ruby extended syntax
    ruby: true
    # whether to enable the fraction extended syntax
    fraction: true
    # whether to enable the fontawesome extended syntax
    fontawesome: true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown: true
    # whether to show the full text content in RSS
    rssFullText: false
    # Table of the contents config
    toc:
      # whether to enable the table of the contents
      enable: true
      # whether to keep the static table of the contents in front of the post
      keepStatic: false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto: false
    # KaTeX mathematical formulas
    math:
      enable: true
      # default inline delimiter is $ ... $ and \( ... \)
      inlineLeftDelimiter:
      inlineRightDelimiter:
      # default block delimiter is $$ ... $$, \[ ... \:, \begin{equation} ... \end{equation} and some other functions
      blockLeftDelimiter:
      blockRightDelimiter:
      # KaTeX extension copy_tex
      copyTex: true
      # KaTeX extension mhchem
      mhchem: true
    # Code config
    code:
      # whether to show the copy button of the code block
      copy: true
      # the maximum number of lines of displayed code by default
      maxShownLines: 50
    # Mapbox GL JS config
    mapbox:
      # access token of Mapbox GL JS
      accessToken: ""
      # style for the light theme
      lightStyle: "mapbox://styles/mapbox/light-v10?optimize=true"
      # style for the dark theme
      darkStyle: "mapbox://styles/mapbox/dark-v10?optimize=true"
      # whether to add NavigationControl
      navigation: true
      # whether to add GeolocateControl
      geolocate: true
      # whether to add ScaleControl
      scale: true
      # whether to add FullscreenControl
      fullscreen: true
    # social share links in post page
    share:
      enabledd: true
      Twitterdd: false
      Facebookdd: false
      Linkedindd: false
      Whatsappdd: false
      Pinterestdd: false
      Tumblrdd: false
      HackerNewsdd: false
      Redditdd: false
      VKdd: false
      Bufferdd: false
      Xingdd: false
      Linedd: false
      Instapaperdd: false
      Pocketdd: false
      Flipboarddd: false
      Weibodd: false
      Bloggerdd: false
      Baidudd: false
      Odnoklassnikidd: false
      Evernotedd: false
      Skypedd: false
      Trellodd: false
      Mixdd: false
    # Comment config
    comment:
      enable: true
      # Disqus comment config
      disqus:
        enable: false
        # disqus shortname to use Disqus
        shortname: 
      utterances:
        enable: true
        repo: ChenYi015/chenyi015.github.io
        issueTerm: pathname
        label: comment
        lightTheme: github-light
        darkTheme: github-dark
  #  TypeIt config
  typeit:
    # typing speed between each step (measured in milliseconds)
    speed: 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed: 1000
    # character used for the cursor (HTML format is supported)
    cursorChar: "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration: 1
# Markup related config in Hugo
markup:
  # Syntax Highlighting
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses: false
    style: monokai
    tabWidth: 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  goldmark:
    extensions:
      definitionListd: true
      footnoted: true
      linkifyd: true
      strikethroughd: true
      tabled: true
      taskListd: true
      typographerd: true
    renderer:
      # whether to use HTML tags directly in the document
      unsafed: true
  # Table Of Contents settings
  tableOfContents:
    startLevel: 1
    endLevel: 3
# Sitemap config
sitemap:
  changefreq: "weekly"
  filename: "sitemap.xml"
  priority: 0.5
# Permalinks config
Permalinks:
  # posts = ":year/:month/:filename"
  posts: ":filename"
# Options to make output .md files
mediaTypes:
  "text/plain":
    suffixes: ["md"]
# Options to make output .md files
outputFormats:
  MarkDown:
    mediaType: "text/plain"
    isPlainText: true
    isHTML: false
# Options to make hugo output files
outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML", "MarkDown"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML", "RSS"]
  taxonomyTerm: ["HTML"]